exclude: [
    "README.md",
    "node_modules",
    "Gruntfile.js",
    "package.json"
]

repository: smart-on-fhir/smart-on-fhir.github.io


#baseurl: "https://docs.smarthealthit.org/"
#baseurl: "http://localhost:4000/"
markdown: kramdown
github_branch: master
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
